markdown:       kramdown
highlighter:    false
#permalink:      pretty

exclude:
  - "img/old/"
  - "LICENSE.md"
  - "node_modules/"
  - "package.json"
  - "params.json"
  - "Readme.md"

title: Notepad2-mod
description: Notepad2-mod, a Notepad2 fork, a fast and light-weight Notepad-like text editor with syntax highlighting
google_analytics: UA-34374820-1
show_downloads: true
theme: jekyll-theme-tactile